var weatherIcons = {
    "200" : ["thunder.png", "rain_medium.png"],
    "201" : ["thunder.png", "rain_heavy.png"],
    "202" : ["thunder.png", "rain_heavy.png"],
    "210" : ["thunder.png"],
    "211" : ["thunder.png"],
    "212" : ["thunder.png"],
    "221" : ["thunder.png"],
    "230" : ["thunder.png", "drizzle.png"],
    "231" : ["thunder.png", "drizzle.png"],
    "232" : ["thunder.png", "drizzle.png"],
    "300" : ["drizzle.png"],
    "301" : ["drizzle.png"],
    "302" : ["drizzle.png"],
    "310" : ["rain_medium.png"],
    "311" : ["rain_heavy.png"],
    "312" : ["rain_heavy.png"],
    "321" : ["showers.png"],
    "500" : ["rain_medium.png"],
    "501" : ["rain_heavy.png"],
    "502" : ["rain_heavy.png"],
    "503" : ["rain_heavy.png"],
    "504" : ["rain_heavy.png"],
    "511" : ["rain_medium.png"],
    "520" : ["showers.png"],
    "521" : ["showers.png"],
    "522" : ["showers.png"],
    "600" : ["snow.png"],
    "601" : ["snow.png"],
    "602" : ["snow_strong.png"],
    "622" : ["snow.png"],
    "611" : ["sleet.png"],
    "621" : ["showers.png"],
    "701" : ["mist.png"],
    "711" : ["mist.png"],
    "721" : ["haze.png"],
    "731" : ["mist.png"],
    "741" : ["fog.png"],
    "800" : ["clear_day.png"],
    "801" : ["half_day.png"],
    "802" : ["half_day.png"],
    "803" : ["half_day.png"],
    "804" : ["cloudy.png"],
    "900" : ["tornado.png"],
    "901" : ["tornado.png"],
    "902" : ["tornado.png"],
    "903" : [""],
    "904" : [""],
    "905" : ["wind.png"],
    "906" : ["hail.png"]
};

